#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    sudo -u www-data php artisan container:init
    set -- php -d variables_order=EGPCS /var/www/html/artisan octane:start "$@"
fi

exec "$@"
