FROM php:8.1-alpine

ARG UID=1000
ARG GID=1000
ENV UID=${UID}
ENV GID=${GID}

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
COPY --from=spiralscout/roadrunner:2.12.2 /usr/bin/rr /usr/bin/rr

# Allow Composer to be run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN apk add --no-cache --update \
      sudo \
      wireguard-tools \
      nodejs \
      npm \
    && install-php-extensions sockets pdo_pgsql zip apcu opcache redis gd intl \
    && echo "Defaults lecture = never" >> /etc/sudoers \
    && echo "www-data ALL=(root) NOPASSWD: /usr/bin/wg-quick, /usr/bin/wg, /usr/bin/tee" >> /etc/sudoers.d/www-data

WORKDIR /var/www/html

RUN addgroup --gid ${GID} www
RUN adduser --uid ${UID} --shell /bin/bash --ingroup www --disabled-password www

USER www

COPY --chown=www:www . ./
