FROM composer:latest as vendor_builder

ENV COMPOSER_ALLOW_SUPERUSER 1

WORKDIR /app
COPY composer.* /app/
RUN composer install -q --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs --optimize-autoloader --no-suggest

FROM node:16-alpine3.16 as node_builder

COPY . /app/
WORKDIR /app
COPY --from=vendor_builder /app/vendor /app/vendor
RUN npm i && npm run production

FROM nginx:alpine

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=node_builder /app/public /var/www/html/public
RUN chown -R nginx:nginx /var/www/html
