version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: app
        command: sh -c "php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=0.0.0.0 --rpc-port=6001 --port=80 --watch"
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./:/var/www/html
        networks:
            - wg-admin

    db:
        image: postgres:14-alpine
        container_name: db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: laravel
            POSTGRES_USER: laravel
            POSTGRES_DB: laravel
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - wg-admin

    redis:
        image: redis:7.0-alpine3.17
        volumes:
            - rddata:/data
        ports:
            - "6379:6379"
        networks:
            - wg-admin

networks:
    wg-admin:
        driver: bridge

volumes:
    dbdata:
        driver: local
    rddata:
        driver: local
