FROM composer:latest as vendor_builder

ENV COMPOSER_ALLOW_SUPERUSER 1

WORKDIR /app
COPY composer.* /app/
RUN composer install -q --no-dev --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs --optimize-autoloader --no-suggest

FROM node:16-alpine3.16 as node_builder

COPY . /app/
COPY --from=vendor_builder /app/vendor /app/vendor
WORKDIR /app
RUN npm i && npm run production

FROM php:8.1-alpine3.16

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
COPY --from=spiralscout/roadrunner:2.12.2 /usr/bin/rr /usr/bin/rr

RUN apk add --no-cache --update \
      sudo \
      wireguard-tools \
    && install-php-extensions pdo_pgsql zip redis gd intl \
    && echo "Defaults lecture = never" >> /etc/sudoers \
    && echo "www-data ALL=(root) NOPASSWD: /usr/bin/wg-quick, /usr/bin/wg, /usr/bin/tee, /bin/rm" >> /etc/sudoers.d/www-data

WORKDIR /var/www/html

COPY ./docker/php/docker-php-entrypoint /usr/local/bin/docker-php-entrypoint
COPY . ./
COPY --from=vendor_builder /app/vendor /var/www/html/vendor
COPY --from=node_builder /app/public /var/www/html/public
RUN chown -R 82:82 /var/www/html

CMD ["php", "-d", "variables_order=EGPCS", "/var/www/html/artisan", "octane:start"]
