FROM node:16-alpine3.16 as node_builder

COPY . /app/
WORKDIR /app
RUN npm i && npm run production

FROM nginx:alpine3.16

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=node_builder /app/public /var/www/html/public
RUN chown -R nginx:nginx /var/www/html
