version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - wg-admin

    webserver:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./:/var/www/html
        networks:
            - wg-admin

    db:
        image: postgres:14-alpine
        container_name: db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: laravel
            POSTGRES_USER: laravel
            POSTGRES_DB: laravel
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - wg-admin

networks:
    wg-admin:
        driver: bridge

volumes:
    dbdata:
        driver: local
