name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        run: |
          docker build . --file Dockerfile-php --tag $DOCKER_LOGIN/wg-admin:${{ github.event.release.tag_name }} --tag $DOCKER_LOGIN/wg-admin:latest
      - name: Push image to Private Docker
        env:
          DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        run: |
          echo "$DOCKER_PASSWD" | docker login --username "$DOCKER_LOGIN" --password-stdin
          docker push -a $DOCKER_LOGIN/wg-admin
